name: po_focus
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-Light.ttf

